package com.finalprojectp1.view.profile;

import java.awt.Color;
import net.miginfocom.swing.MigLayout;

/**
 * @author Isaac M
 */
public class VentanaDriverProfile extends javax.swing.JFrame {

    /**
     * Creates new form VentanaDriverProfile
     */
    public VentanaDriverProfile() {
        initComponents();
        init();
        setExtendedState(MAXIMIZED_BOTH);
    }

    private void init() {
        configurarLayout();
        editCamp();
    }

    private void configurarLayout() {
        contenedor.setLayout(new MigLayout("fill"));
        contenedor.add(cuerpo, "align 50% 50%");
    }

    private void editCamp() {
        //Campo donde se muestra el color
        String colorHex = "#0066FF"; // aca iran los distintos valores de color obtenidos.
        txtColor.setText(colorHex);
        // Convertir el color hexadecimal a objeto Color
        Color colorA = Color.decode(colorHex);
        // Aplicar el color de fondo
        txtColor.setBackground(colorA);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        cuerpo = new com.finalprojectp1.view.signin.swing.PanelRound();
        titleConductor = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        number = new javax.swing.JLabel();
        txtNumber = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        titleAuto = new javax.swing.JLabel();
        modelo = new javax.swing.JLabel();
        txtCar = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JLabel();
        placa = new javax.swing.JLabel();
        color = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        menu = new javax.swing.JMenuBar();
        tresRayaMenu = new javax.swing.JMenu();
        irHistory = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        cerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        contenedor.setBackground(new java.awt.Color(230, 230, 230));

        cuerpo.setBackground(new java.awt.Color(255, 255, 255));
        cuerpo.setRoundBottomLeft(40);
        cuerpo.setRoundBottomRight(40);
        cuerpo.setRoundTopLeft(40);
        cuerpo.setRoundTopRight(40);

        titleConductor.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        titleConductor.setForeground(new java.awt.Color(51, 51, 51));
        titleConductor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleConductor.setText("Perfil del conductor");

        name.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        name.setForeground(new java.awt.Color(51, 51, 51));
        name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-2.png"))); // NOI18N
        name.setText("Nombre:");

        txtName.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtName.setForeground(new java.awt.Color(51, 51, 51));
        txtName.setText("Gente");

        number.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        number.setForeground(new java.awt.Color(51, 51, 51));
        number.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-3.png"))); // NOI18N
        number.setText("Contacto:");

        txtNumber.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtNumber.setForeground(new java.awt.Color(51, 51, 51));
        txtNumber.setText("1234567890");

        jSeparator1.setForeground(new java.awt.Color(153, 153, 255));

        titleAuto.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        titleAuto.setForeground(new java.awt.Color(51, 51, 51));
        titleAuto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleAuto.setText("Vehículo");

        modelo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        modelo.setForeground(new java.awt.Color(102, 102, 255));
        modelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-8.png"))); // NOI18N
        modelo.setText("Modelo:");

        txtCar.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        txtCar.setForeground(new java.awt.Color(102, 102, 255));
        txtCar.setText("Carro");

        txtPlaca.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        txtPlaca.setForeground(new java.awt.Color(102, 102, 255));
        txtPlaca.setText("ABC-1234");

        placa.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        placa.setForeground(new java.awt.Color(102, 102, 255));
        placa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-6.png"))); // NOI18N
        placa.setText("Placa:");

        color.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        color.setForeground(new java.awt.Color(102, 102, 255));
        color.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-10.png"))); // NOI18N
        color.setText("Color:");

        txtColor.setEditable(false);
        txtColor.setFocusable(false);

        javax.swing.GroupLayout cuerpoLayout = new javax.swing.GroupLayout(cuerpo);
        cuerpo.setLayout(cuerpoLayout);
        cuerpoLayout.setHorizontalGroup(
                cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cuerpoLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(cuerpoLayout.createSequentialGroup()
                                                .addComponent(placa)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
                                        .addComponent(titleAuto, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(number, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(titleConductor, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cuerpoLayout.createSequentialGroup()
                                                .addComponent(modelo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cuerpoLayout.createSequentialGroup()
                                                .addComponent(color)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(61, Short.MAX_VALUE))
        );
        cuerpoLayout.setVerticalGroup(
                cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cuerpoLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(titleConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(number)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumber)
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(titleAuto)
                                .addGap(18, 18, 18)
                                .addGroup(cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPlaca))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
                contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                                .addContainerGap(53, Short.MAX_VALUE)
                                .addComponent(cuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58))
        );
        contenedorLayout.setVerticalGroup(
                contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                                .addContainerGap(29, Short.MAX_VALUE)
                                .addComponent(cuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
        );

        menu.setFocusable(false);
        menu.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N

        tresRayaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        tresRayaMenu.setFocusable(false);
        tresRayaMenu.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        tresRayaMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tresRayaMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        irHistory.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        irHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reloj.png"))); // NOI18N
        irHistory.setText("Historial");
        irHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irHistoryActionPerformed(evt);
            }
        });
        tresRayaMenu.add(irHistory);
        tresRayaMenu.add(jSeparator2);

        cerrarSesion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        cerrarSesion.setText("Cerrar Sesión");
        tresRayaMenu.add(cerrarSesion);

        menu.add(tresRayaMenu);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void irHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irHistoryActionPerformed
        HistorialEscaneos p1 = new HistorialEscaneos();
        p1.setVisible(true);
    }//GEN-LAST:event_irHistoryActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cerrarSesion;
    private javax.swing.JLabel color;
    private javax.swing.JPanel contenedor;
    private com.finalprojectp1.view.signin.swing.PanelRound cuerpo;
    private javax.swing.JMenuItem irHistory;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuBar menu;
    private javax.swing.JLabel modelo;
    private javax.swing.JLabel name;
    private javax.swing.JLabel number;
    private javax.swing.JLabel placa;
    private javax.swing.JLabel titleAuto;
    private javax.swing.JLabel titleConductor;
    private javax.swing.JMenu tresRayaMenu;
    private javax.swing.JLabel txtCar;
    private javax.swing.JTextField txtColor;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtNumber;
    private javax.swing.JLabel txtPlaca;
    // End of variables declaration//GEN-END:variables

    public void setTxtCar(javax.swing.JLabel txtCar) {
        this.txtCar = txtCar;
    }

    public void setTxtColor(javax.swing.JTextField txtColor) {
        this.txtColor = txtColor;
    }

    public void setTxtName(javax.swing.JLabel txtName) {
        this.txtName = txtName;
    }

    public void setTxtNumber(javax.swing.JLabel txtNumber) {
        this.txtNumber = txtNumber;
    }

    public void setTxtPlaca(javax.swing.JLabel txtPlaca) {
        this.txtPlaca = txtPlaca;
    }
}
