package com.finalprojectp1.view.signin;

import com.finalprojectp1.view.signin.swing.SwitchButton;
import com.formdev.flatlaf.FlatClientProperties;
import com.finalprojectp1.controller.signin.EventoCheckSesion;
import com.finalprojectp1.controller.signin.ManejadorEventos;
import com.finalprojectp1.controller.signin.ObtenerInfoLogin;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 * @author Isaac M
 */
public class panelLogin extends javax.swing.JPanel {

    // Atributos adicionales
    private final VentanaRegistro ventana;

    /**
     * Creates new form panelLogin
     *
     * @param ventana
     * @param switchButton
     */
    // Constructor
    public panelLogin(VentanaRegistro ventana, SwitchButton switchButton) {
        this.ventana = ventana;
        initComponents();
        init();
        setSize(850, 510);
        setPreferredSize(new java.awt.Dimension(850, 510));
        ventana.getTglbRoll().setEnabled(false);
    }

    /**
     * Inicializa componentes y configura la interfaz gráfica.
     */
    private void init() {
        customizeCamps();

        panelLg.add(jtCorreo, "align center, wrap");
        panelLg.add(jpContrasena, "align center, wrap");
        panelLg.add(btnLogin, "align center, wrap");
        panelLg.add(jlMandarSign, "align center, wrap");

        new ManejadorEventos(ventana, this);
        checkMantenerSesion.addItemListener(new EventoCheckSesion());

        btnLogTxt.addMouseListener(new ObtenerInfoLogin(this));
    }

    /**
     * Personaliza los campos de entrada agregando placeholders e iconos entre
     * otros.
     */
    private void customizeCamps() {
        jtCorreo.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Correo");
        jpContrasena.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Contraseña");

        jtCorreo.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new ImageIcon(getClass().getResource("/img/icon-4.png")));
        jpContrasena.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new ImageIcon(getClass().getResource("/img/icon-5.png")));

        jpContrasena.putClientProperty(FlatClientProperties.STYLE, "" + "showRevealButton:true;");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLg = new com.finalprojectp1.view.signin.swing.PanelRound();
        jtCorreo = new javax.swing.JTextField();
        jpContrasena = new javax.swing.JPasswordField();
        checkMantenerSesion = new javax.swing.JCheckBox();
        jlCambiarContra = new javax.swing.JLabel();
        jlMandarSign = new javax.swing.JLabel();
        btnLogin = new com.finalprojectp1.view.signin.swing.PanelRound();
        btnLogTxt = new javax.swing.JLabel();
        panelDinamcLg = new com.finalprojectp1.view.signin.swing.PanelRound();
        titlelg = new javax.swing.JLabel();
        image2 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(850, 510));

        panelLg.setBackground(new java.awt.Color(51, 51, 51, 110));
        panelLg.setRoundBottomLeft(40);
        panelLg.setRoundTopLeft(40);

        jtCorreo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jpContrasena.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        checkMantenerSesion.setForeground(new java.awt.Color(51, 51, 51));
        checkMantenerSesion.setText("Recuérdame");

        jlCambiarContra.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlCambiarContra.setForeground(new java.awt.Color(3, 96, 190));
        jlCambiarContra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCambiarContra.setText("¿Has olvidado tu contraseña?");
        jlCambiarContra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlCambiarContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlCambiarContraMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlCambiarContraMouseExited(evt);
            }
        });

        jlMandarSign.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlMandarSign.setForeground(new java.awt.Color(3, 96, 190));
        jlMandarSign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMandarSign.setText("¿No tienes una cuenta? Regístrate");
        jlMandarSign.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMandarSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlMandarSignMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlMandarSignMouseExited(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(131, 46, 205));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setPreferredSize(new java.awt.Dimension(185, 40));

        btnLogTxt.setBackground(new java.awt.Color(255, 255, 255));
        btnLogTxt.setFont(new java.awt.Font("Roboto SemiCondensed SemiBold", 1, 22)); // NOI18N
        btnLogTxt.setForeground(new java.awt.Color(255, 255, 255));
        btnLogTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogTxt.setText("Entrar");
        btnLogTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogTxtMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLoginLayout = new javax.swing.GroupLayout(btnLogin);
        btnLogin.setLayout(btnLoginLayout);
        btnLoginLayout.setHorizontalGroup(
                btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnLogTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnLoginLayout.setVerticalGroup(
                btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnLogTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelLgLayout = new javax.swing.GroupLayout(panelLg);
        panelLg.setLayout(panelLgLayout);
        panelLgLayout.setHorizontalGroup(
                panelLgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLgLayout.createSequentialGroup()
                                .addContainerGap(95, Short.MAX_VALUE)
                                .addGroup(panelLgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jlMandarSign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                                .addGap(94, 94, 94))
                        .addGroup(panelLgLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(panelLgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(checkMantenerSesion)
                                        .addComponent(jtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                        .addComponent(jpContrasena)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLgLayout.createSequentialGroup()
                                                .addComponent(jlCambiarContra)
                                                .addGap(51, 51, 51)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLgLayout.setVerticalGroup(
                panelLgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelLgLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jpContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(checkMantenerSesion)
                                .addGap(63, 63, 63)
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jlMandarSign)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlCambiarContra)
                                .addContainerGap(60, Short.MAX_VALUE))
        );

        panelDinamcLg.setBackground(new java.awt.Color(131, 46, 205));
        panelDinamcLg.setRoundBottomRight(40);
        panelDinamcLg.setRoundTopRight(40);

        titlelg.setFont(new java.awt.Font("Roboto Slab", 1, 36)); // NOI18N
        titlelg.setForeground(new java.awt.Color(255, 255, 255));
        titlelg.setText("Iniciar Sesión");

        image2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/02.gif"))); // NOI18N

        javax.swing.GroupLayout panelDinamcLgLayout = new javax.swing.GroupLayout(panelDinamcLg);
        panelDinamcLg.setLayout(panelDinamcLgLayout);
        panelDinamcLgLayout.setHorizontalGroup(
                panelDinamcLgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelDinamcLgLayout.createSequentialGroup()
                                .addGroup(panelDinamcLgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelDinamcLgLayout.createSequentialGroup()
                                                .addGap(120, 120, 120)
                                                .addComponent(titlelg))
                                        .addGroup(panelDinamcLgLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(image2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelDinamcLgLayout.setVerticalGroup(
                panelDinamcLgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelDinamcLgLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(titlelg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(image2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panelLg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(panelDinamcLg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelLg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelDinamcLg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogTxtMouseEntered
        btnLogin.setBackground(new Color(131, 75, 210));
    }//GEN-LAST:event_btnLogTxtMouseEntered

    private void btnLogTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogTxtMouseExited
        btnLogin.setBackground(new Color(131, 46, 205));
    }//GEN-LAST:event_btnLogTxtMouseExited

    private void jlMandarSignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMandarSignMouseEntered
        jlMandarSign.setForeground(new Color(204, 255, 255));
        jlMandarSign.setText("<html><u>¿No tienes una cuenta? Regístrate</u></html>");
    }//GEN-LAST:event_jlMandarSignMouseEntered

    private void jlMandarSignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMandarSignMouseExited
        jlMandarSign.setForeground(new Color(3, 96, 190));
        jlMandarSign.setText("¿No tienes una cuenta? Regístrate");
    }//GEN-LAST:event_jlMandarSignMouseExited

    private void jlCambiarContraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCambiarContraMouseEntered
        jlCambiarContra.setForeground(new Color(204, 255, 255));
        jlCambiarContra.setText("<html><u>¿Has olvidado tu contraseña?</u></html>");
    }//GEN-LAST:event_jlCambiarContraMouseEntered

    private void jlCambiarContraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCambiarContraMouseExited
        jlCambiarContra.setForeground(new Color(3, 96, 190));
        jlCambiarContra.setText("¿Has olvidado tu contraseña?");
    }//GEN-LAST:event_jlCambiarContraMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnLogTxt;
    private com.finalprojectp1.view.signin.swing.PanelRound btnLogin;
    private javax.swing.JCheckBox checkMantenerSesion;
    private javax.swing.JLabel image2;
    private javax.swing.JLabel jlCambiarContra;
    private javax.swing.JLabel jlMandarSign;
    private javax.swing.JPasswordField jpContrasena;
    private javax.swing.JTextField jtCorreo;
    private com.finalprojectp1.view.signin.swing.PanelRound panelDinamcLg;
    private com.finalprojectp1.view.signin.swing.PanelRound panelLg;
    private javax.swing.JLabel titlelg;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getJlCambiarContra() {
        return jlCambiarContra;
    }

    public javax.swing.JLabel getJlMandarSign() {
        return jlMandarSign;
    }

    public javax.swing.JCheckBox getCheckMantenerSesion() {
        return checkMantenerSesion;
    }

    public javax.swing.JPasswordField getJpContrasena() {
        return jpContrasena;
    }

    public javax.swing.JTextField getJtCorreo() {
        return jtCorreo;
    }

}
