package com.finalprojectp1.view.signin;

import com.finalprojectp1.controller.signin.SwitchRolHandler;
import com.formdev.flatlaf.FlatClientProperties;
import com.finalprojectp1.controller.signin.ObtenerInfoSignPasajero;
import com.finalprojectp1.controller.signin.ManejadorEventos;
import com.finalprojectp1.view.signin.swing.PanelConImagen;
import java.awt.*;
import java.awt.event.KeyEvent;
import javax.swing.*;
import net.miginfocom.swing.MigLayout;

/*
VentanaRegistro representa la interfaz de registro de usuarios.
Proporciona campos para ingresar nombre, apellido, número, correo y contraseña.
También permite cambiar de rol mediante un interruptor.
 */
/**
 * @author Isaac M
 */
public class VentanaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private panelLogin p1;
    private ManejadorEventos manejador;

    public VentanaRegistro() {
        initComponents();
        init();
        // Crear una sola instancia de los paneles y usarlas en toda la ventana
        p1 = new panelLogin(this, tglbRoll);
        // Pasar las mismas instancias a ManejadorEventos
        manejador = new ManejadorEventos(this, p1);
        setTitle("Registro"); // Titulo de la ventana
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize(); // Obtener tamaño de pantalla
        setMinimumSize(screenSize);  // Evitar que sea más pequeña
        setExtendedState(MAXIMIZED_BOTH); // Maximimizar ventana
        tglbRoll.setEnabled(true);
    }

    /**
     * Personaliza los campos de entrada agregando placeholders e iconos entre
     * otros.
     */
    private void customizeCamps() {
        // Placeholders
        jtNombre.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nombre");
        jtApellido.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Apellido");
        jtNumero.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Numero");
        jtCorreo.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Correo");
        jpContrasena.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Contraseña");

        // Iconos
        jtNombre.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new ImageIcon(getClass().getResource("/img/icon-1.png")));
        jtApellido.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new ImageIcon(getClass().getResource("/img/icon-2.png")));
        jtNumero.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new ImageIcon(getClass().getResource("/img/icon-3.png")));
        jtCorreo.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new ImageIcon(getClass().getResource("/img/icon-4.png")));
        jpContrasena.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new ImageIcon(getClass().getResource("/img/icon-5.png")));

        // Ver y Ocultar
        jpContrasena.putClientProperty(FlatClientProperties.STYLE, "" + "showRevealButton:true;");
    }

    /**
     * Inicializa componentes y configura la interfaz gráfica.
     */
    private void init() {
        customizeCamps(); // llamada al metodo que personaliza los campos
        panelContenido.setLayout(new MigLayout("fill", "[grow]", "[][]"));
        panelContenido.add(panelRoll, "dock north, growx");
        panelContenido.add(panelMover, "center");

        panelSign.add(btnRegistrar, "align center");
        panelSign.add(lblMandarLogin, "align center, wrap");

        tglbRoll.addEventSwitchSelected(new SwitchRolHandler(this));

        btnRgTxt.addMouseListener(new ObtenerInfoSignPasajero(this));
    }

    public void mostrarRegistro() {
        // metodo para poder volver al registro desde otros paneles
        panelMover.removeAll();
        panelMover.add(panelPrincipal, BorderLayout.CENTER);
        panelMover.revalidate();
        panelMover.repaint();
    }

    public void cambiarPanel(JPanel nuevoPanel) {
        // metodo para cambiar de paneles
        nuevoPanel.setSize(panelMover.getWidth(), panelMover.getHeight());
        nuevoPanel.setLocation(0, 0);

        panelMover.removeAll();
        panelMover.add(nuevoPanel, BorderLayout.CENTER);
        panelMover.revalidate();
        panelMover.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTransicion = new javax.swing.JPanel();
        panelContenido = new PanelConImagen("img/01.png");
        panelMover = new javax.swing.JPanel();
        panelPrincipal = new javax.swing.JPanel();
        panelDinamico = new com.finalprojectp1.view.signin.swing.PanelRound();
        title = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();
        panelSign = new com.finalprojectp1.view.signin.swing.PanelRound();
        jtNombre = new javax.swing.JTextField();
        jtApellido = new javax.swing.JTextField();
        jtNumero = new javax.swing.JTextField();
        jtCorreo = new javax.swing.JTextField();
        jpContrasena = new javax.swing.JPasswordField();
        btnRegistrar = new com.finalprojectp1.view.signin.swing.PanelRound();
        btnRgTxt = new javax.swing.JLabel();
        lblMandarLogin = new javax.swing.JLabel();
        panelRoll = new javax.swing.JPanel();
        tglbRoll = new com.finalprojectp1.view.signin.swing.SwitchButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelMover.setBackground(new java.awt.Color(204, 0, 0));
        panelMover.setOpaque(false);
        panelMover.setPreferredSize(new java.awt.Dimension(856, 510));

        panelPrincipal.setBackground(new java.awt.Color(102, 255, 102));
        panelPrincipal.setOpaque(false);

        panelDinamico.setBackground(new java.awt.Color(71, 23, 246));
        panelDinamico.setRoundBottomLeft(40);
        panelDinamico.setRoundTopLeft(40);

        title.setFont(new java.awt.Font("Roboto Slab", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Registrarme");

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/02.gif"))); // NOI18N

        javax.swing.GroupLayout panelDinamicoLayout = new javax.swing.GroupLayout(panelDinamico);
        panelDinamico.setLayout(panelDinamicoLayout);
        panelDinamicoLayout.setHorizontalGroup(
                panelDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelDinamicoLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(17, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDinamicoLayout.createSequentialGroup()
                                .addContainerGap(122, Short.MAX_VALUE)
                                .addComponent(title)
                                .addGap(127, 127, 127))
        );
        panelDinamicoLayout.setVerticalGroup(
                panelDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelDinamicoLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(27, Short.MAX_VALUE))
        );

        panelSign.setBackground(new java.awt.Color(51, 51, 51, 110));
        panelSign.setRoundBottomRight(40);
        panelSign.setRoundTopRight(40);

        jtNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtApellido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtNumeroKeyTyped(evt);
            }
        });

        jtCorreo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jpContrasena.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnRegistrar.setBackground(new java.awt.Color(71, 23, 246));

        btnRgTxt.setFont(new java.awt.Font("Roboto Condensed SemiBold", 0, 22)); // NOI18N
        btnRgTxt.setForeground(new java.awt.Color(255, 255, 255));
        btnRgTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRgTxt.setText("Registrar");
        btnRgTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRgTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRgTxtMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRgTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnRegistrarLayout = new javax.swing.GroupLayout(btnRegistrar);
        btnRegistrar.setLayout(btnRegistrarLayout);
        btnRegistrarLayout.setHorizontalGroup(
                btnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnRgTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
        );
        btnRegistrarLayout.setVerticalGroup(
                btnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnRgTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        lblMandarLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblMandarLogin.setForeground(new java.awt.Color(3, 96, 190));
        lblMandarLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMandarLogin.setText("¿Ya tienes una cuenta? Iniciar sesión!");
        lblMandarLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMandarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMandarLoginMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMandarLoginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelSignLayout = new javax.swing.GroupLayout(panelSign);
        panelSign.setLayout(panelSignLayout);
        panelSignLayout.setHorizontalGroup(
                panelSignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelSignLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(panelSignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelSignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jpContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblMandarLogin)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSignLayout.createSequentialGroup()
                                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)))
                                .addContainerGap(68, Short.MAX_VALUE))
        );
        panelSignLayout.setVerticalGroup(
                panelSignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelSignLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jpContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(lblMandarLogin)
                                .addGap(28, 28, 28)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
                panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(panelDinamico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(panelSign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelPrincipalLayout.setVerticalGroup(
                panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelDinamico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelSign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelMoverLayout = new javax.swing.GroupLayout(panelMover);
        panelMover.setLayout(panelMoverLayout);
        panelMoverLayout.setHorizontalGroup(
                panelMoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelMoverLayout.setVerticalGroup(
                panelMoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelRoll.setBackground(new java.awt.Color(0, 153, 153));
        panelRoll.setOpaque(false);
        panelRoll.setPreferredSize(new java.awt.Dimension(205, 60));

        tglbRoll.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tglbRoll.setRound(999);
        tglbRoll.setSwitchColor(new java.awt.Color(0, 153, 102));
        tglbRoll.setSwitchOffColor(new java.awt.Color(51, 0, 204));

        javax.swing.GroupLayout panelRollLayout = new javax.swing.GroupLayout(panelRoll);
        panelRoll.setLayout(panelRollLayout);
        panelRollLayout.setHorizontalGroup(
                panelRollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRollLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tglbRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(1194, Short.MAX_VALUE))
        );
        panelRollLayout.setVerticalGroup(
                panelRollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRollLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tglbRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
                panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelContenidoLayout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(panelMover, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelContenidoLayout.setVerticalGroup(
                panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelContenidoLayout.createSequentialGroup()
                                .addComponent(panelRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(panelMover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelTransicionLayout = new javax.swing.GroupLayout(panelTransicion);
        panelTransicion.setLayout(panelTransicionLayout);
        panelTransicionLayout.setHorizontalGroup(
                panelTransicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1370, Short.MAX_VALUE)
                        .addGroup(panelTransicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTransicionLayout.setVerticalGroup(
                panelTransicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 699, Short.MAX_VALUE)
                        .addGroup(panelTransicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelTransicion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelTransicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRgTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRgTxtMouseEntered
        btnRegistrar.setBackground(new Color(100, 62, 241));
    }//GEN-LAST:event_btnRgTxtMouseEntered

    private void btnRgTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRgTxtMouseExited
        btnRegistrar.setBackground(new Color(71, 23, 246));
    }//GEN-LAST:event_btnRgTxtMouseExited

    private void lblMandarLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMandarLoginMouseEntered
        lblMandarLogin.setForeground(new Color(204, 255, 255));
        lblMandarLogin.setText("<html><u>¿Ya tienes una cuenta? Iniciar sesión!</u></html>");
    }//GEN-LAST:event_lblMandarLoginMouseEntered

    private void lblMandarLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMandarLoginMouseExited
        lblMandarLogin.setForeground(new Color(3, 96, 190));
        lblMandarLogin.setText("¿Ya tienes una cuenta? Iniciar sesión!");
    }//GEN-LAST:event_lblMandarLoginMouseExited

    private void jtNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNumeroKeyTyped
        // Obtiene el carácter que el usuario ha ingresado o presionado.
        char c = evt.getKeyChar();
        // Verifica si el carácter ingresado NO es un dígito, tecla de retroceso o eliminar.
        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE) {
            // Ignorar el carácter no numérico
            evt.consume();
        }
    }//GEN-LAST:event_jtNumeroKeyTyped

    // Atributos
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.finalprojectp1.view.signin.swing.PanelRound btnRegistrar;
    private javax.swing.JLabel btnRgTxt;
    private javax.swing.JLabel imagen;
    private javax.swing.JPasswordField jpContrasena;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtCorreo;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtNumero;
    private javax.swing.JLabel lblMandarLogin;
    private javax.swing.JPanel panelContenido;
    private com.finalprojectp1.view.signin.swing.PanelRound panelDinamico;
    private javax.swing.JPanel panelMover;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRoll;
    private com.finalprojectp1.view.signin.swing.PanelRound panelSign;
    private javax.swing.JPanel panelTransicion;
    private com.finalprojectp1.view.signin.swing.SwitchButton tglbRoll;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    public com.finalprojectp1.view.signin.swing.SwitchButton getTglbRoll() {
        return tglbRoll;
    }

    public javax.swing.JPanel getPanelMover() {
        return panelMover;
    }

    public javax.swing.JLabel getLblMandarLogin() {
        return lblMandarLogin;
    }

    public javax.swing.JPasswordField getJpContrasena() {
        return jpContrasena;
    }

    public javax.swing.JTextField getJtApellido() {
        return jtApellido;
    }

    public javax.swing.JTextField getJtCorreo() {
        return jtCorreo;
    }

    public javax.swing.JTextField getJtNombre() {
        return jtNombre;
    }

    public javax.swing.JTextField getJtNumero() {
        return jtNumero;
    }

}
